Repository xsdk-project/xsdk-examples, pull requests merged in 2023-05, with the labels that each got.

#23 added tasmanian-magma example
  CMakeLists.txt
  README.md
  tasmanian/CMakeLists.txt
  tasmanian/README.md
  tasmanian/example_unstructured_grid.cpp
Labels: new example

#24 added heffte-magma example
  CMakeLists.txt
  README.md
  heffte/CMakeLists.txt
  heffte/README.md
  heffte/heffte_example_gpu.cpp
Labels: new example

#25 Add dealii examples
  CMakeLists.txt
  README.md
  dealii/CMakeLists.txt
  dealii/README.md
  dealii/petsc_trilinos/CMakeLists.txt
  dealii/petsc_trilinos/README.md
  dealii/petsc_trilinos/petsc_trilinos.cc
  dealii/sundials/CMakeLists.txt
  dealii/sundials/README.md
  dealii/sundials/sundials.cc
Labels: new example

#36 Add dealii-precice example
  CMakeLists.txt
  README.md
  dealii/CMakeLists.txt
  dealii/precice/CMakeLists.txt
  dealii/precice/README.md
  dealii/precice/boundary_condition.cc
  dealii/precice/clean
  dealii/precice/laplace_problem.cc
  dealii/precice/precice-config.xml
  dealii/precice/runtargets.sh
Labels: new example

#35 petsc: update test code from @3.18 for xsdk-examples@0.4.0, and add a run target for hip
  README.md
  petsc/CMakeLists.txt
  petsc/ex19.c
  petsc/makefile
  petsc/output/ex19_cuda_1.out
  petsc/output/ex19_hip.out
  petsc/output/ex19_ml.out
Labels: enhancement

#43 Add new MFEM examples for v0.4.0
  CMakeLists.txt
  README.md
  amrex/CMakeLists.txt
  amrex/sundials/CMakeLists.txt
  cmake/FindAMReX.cmake
  cmake/FindMFEM.cmake
  hypre/CMakeLists.txt
  mfem/CMakeLists.txt
  mfem/data/amr-quad.mesh
  mfem/data/disc-nurbs.mesh
  mfem/data/periodic-cube.mesh
  mfem/data/periodic-segment.mesh
  mfem/data/periodic-square.mesh
  mfem/data/pumi/geom/Kova.dmg
  mfem/data/pumi/geom/Kova.x_t
  mfem/data/pumi/parallel/KovaLinear/Kova-linear-10k_2p0.smb
  mfem/data/pumi/parallel/KovaLinear/Kova-linear-10k_2p1.smb
  mfem/ginkgo/CMakeLists.txt
  mfem/hiop/CMakeLists.txt
  mfem/hiop/README.md
  mfem/hiop/adv.cpp
  mfem/hypre-superlu/CMakeLists.txt
  mfem/hypre/CMakeLists.txt
  mfem/hypre/magnetic-diffusion.cpp
  mfem/petsc/CMakeLists.txt
  mfem/pumi/CMakeLists.txt
  mfem/pumi/README.md
  mfem/pumi/adapt.cpp
  mfem/strumpack/CMakeLists.txt
  mfem/sundials/CMakeLists.txt
  petsc/CMakeLists.txt
  strumpack/CMakeLists.txt
  sundials/CMakeLists.txt
  trilinos/CMakeLists.txt
Labels: enhancement, new example
